// public/react/Auth/Login.jsx
const { useState } = React;
const { site_url } = globalProps;

const Page = () => {
  const [form, setForm] = useState({
    email: "",
    password: "",
    errors: {},
  });
  const handleChange = (e) => {
    setForm({
      ...form,
      [e.target.name || e.target.id]: e.target.value,
    });
  };
  const handleSubmit = async (e) => {
    e.preventDefault();
    try {
      const { data } = await api.post("/auth/login", form);
      if (data.success) location.href = site_url + "/";
    } catch ({ response }) {
      setForm({
        ...form,
        errors: response.data.errors,
      });
    }
  };
  return (
    <div class="container py-4">
      <div class="row justify-content-center">
        <div class="col-11 col-md-8 p-0">
          <div class="card">
            <h5 class="card-header">Login</h5>
            <div class="card-body">
              <form onSubmit={handleSubmit}>
                <div class="form-floating mb-2">
                  <input
                    type="email"
                    className={`form-control ${
                      form.errors.email ? "is-invalid" : ""
                    }`}
                    id="email"
                    placeholder="Email"
                    onChange={handleChange}
                  />
                  <label for="email">Email</label>
                  {form.errors.email && (
                    <strong class="invalid-feedback">
                      {form.errors.email}
                    </strong>
                  )}
                </div>
                <div class="form-floating mb-2">
                  <input
                    type="password"
                    className={`form-control ${
                      form.errors.password ? "is-invalid" : ""
                    }`}
                    id="password"
                    placeholder="Password"
                    onChange={handleChange}
                  />
                  <label for="password">Password</label>
                  {form.errors.password && (
                    <strong class="invalid-feedback">
                      {form.errors.password}
                    </strong>
                  )}
                </div>
                <button class="btn btn-sm btn-primary">
                  <i class="bi bi-save me-2"></i>Login
                </button>
                <p>
                  Dont have an account ?
                  <a href={site_url + "/auth/register"}>Register</a>
                </p>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

// public/vue/Auth/Login.vue
<template>
  <div class="container py-4">
    <div class="row justify-content-center">
      <div class="col-11 col-md-8 p-0">
        <div class="card">
          <h5 class="card-header">Login</h5>
          <div class="card-body">
            <form @submit.prevent="handleSubmit">
              <div class="form-floating mb-2">
                <input
                  type="email"
                  :class="`form-control ${
                    form.errors.email ? 'is-invalid' : ''
                  }`"
                  id="email"
                  v-model="form.email"
                  placeholder="Email"
                />
                <label for="email">Email</label>
                <strong class="invalid-feedback" v-if="form.errors.email">
                  {{ form.errors.email }}
                </strong>
              </div>
              <div class="form-floating mb-2">
                <input
                  type="password"
                  :class="`form-control ${
                    form.errors.password ? 'is-invalid' : ''
                  }`"
                  id="password"
                  v-model="form.password"
                  placeholder="Password"
                />
                <label for="password">Password</label>
                <strong class="invalid-feedback" v-if="form.errors.password">
                  {{ form.errors.password }}
                </strong>
              </div>
              <button class="btn btn-sm btn-primary">
                <i class="bi bi-save me-2"></i>Login
              </button>
              <p>
                Dont have an account ?
                <a :href="site_url + '/auth/register'">Register</a>
              </p>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>
<script>
const defineComponent = {
  data: () => ({
    form: {
      email: "",
      password: "",
      errors: {},
    },
  }),
  methods: {
    async handleSubmit() {
      try {
        const { data } = await api.post("/auth/login", this.form);
        if (data.success) location.href = this.site_url + "/";
      } catch ({ response }) {
        this.form.errors = response.data.errors;
      }
    },
  },
};
</script>
